name: uselytics
services:
  # dashboard:
  #   build:
  #     context: ./dashboard
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #     - postgres
  #     - redis
  #   environment:
  #     - RUST_API_URL=http://api:8000
  #     - POSTGRES_HOST=postgres
  #     - REDIS_HOST=redis

  # api:
  #   build:
  #     context: ./api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - RUST_LOG=info
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uselytics
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.11-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data: {}
  redis-data: {}